### PR TITLE
Bootstrap Version Update

### PR DESCRIPTION
**Pull request by ssuds**
Updated bootstrap to 3.3.6 
No issues noted

### CODE REVIEW

**Comment by mass** [comment]
Seeing the two commits at the end cancel each other out, you should just reset the branch to the bootstrap update commit and then force-push here again. That'll keep things clean

**Comment by ssuds** [comment]
They don't entirely cancel each other out, the changes to partners.php in the second commit persist on through. I can go back to the first commit and make a new commit only changing that if preferred.

**Comment by mass** [comment]
Oh, I didn't  see that. Yeah it's probably easier to `git commit --amend` the first commit and  force push. Although, a `git rebase -i` is really what is correct here, but that's pretty advanced git stuff so I wouldn't expect it lol

**Comment by ssuds** [comment]
Alright, the commit history should be cleaned up to merge now.

**Pull request merged**
